CREATE DATABASE proyectoprog2 CHARACTER SET utf8mb4;
CREATE TABLE users(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(100) NOT NULL,
apellido VARCHAR(100) NOT NULL,
email VARCHAR(250) NOT NULL,
password VARCHAR(250) NOT NULL, 
image VARCHAR(200) NOT NULL,
fecha DATE NOT NULL,
productos INT UNSIGNED NOT NULL
);

ALTER TABLE users 
ADD seguidores INT UNSIGNED NOT NULL,
ADD comentarios INT UNSIGNED NOT NULL;

CREATE TABLE product(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
modelo VARCHAR(200) NOT NULL,
image VARCHAR(200) NOT NULL,
descripcion VARCHAR(300) NOT NULL,
comentarios VARCHAR(300) NOT NULL,
fecha DATE NOT NULL
);

CREATE TABLE comentarios(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
comentario VARCHAR(300) NOT NULL,
fecha DATE NOT NULL
);

ALTER TABLE comentarios 
ADD users_id INT NOT NULL;

ALTER TABLE comentarios
ADD FOREIGN KEY (users_id) REFERENCES users(id);

ALTER TABLE product
ADD comentarios_id INT UNSIGNED NOT NULL;

ALTER TABLE product
ADD FOREIGN KEY (comentarios_id) REFERENCES comentarios(id);

ALTER TABLE comentarios 
ADD product_id INT UNSIGNED NOT NULL;

ALTER TABLE comentarios
ADD FOREIGN KEY (product_id) REFERENCES product(id);